Feature/is27 booking api
Mash-Up-MapC/MapC-backend pull request #46
Opened 2018-08-31 18:23 UTC by KiWooyoung

## Description
예약 API 구현하기

## Related Tickets
* 예약 API 구현하기(#27)

<br>

## Check List
- [x] PR 제목은 유의미한가?
- [ ] PR 내용만 보고도 이해할 수 있을 정도로 기술되었는가?
- [x] 관련 issue를 적었는가?
- [ ] 관련 reference가 있다면 함께 적었는가?
- [x] Reviewer, Assginess, Label을 지정했는가?

2018-08-31 19:40 UTC, opklnm102 requested changes

2018-08-31 19:40 UTC, opklnm102 commented on src/main/java/kr/co/mashup/mapc/dto/BookingDto.java
> +            log.info(this.toString());
불필요한듯..?

2018-08-31 19:40 UTC, opklnm102 commented on src/main/java/kr/co/mashup/mapc/service/BookingService.java
> +        Optional<Tourist> tourist = touristRepository.findByUuid(body.getUuid());
optional 변수명은 아래중에 1개로 명시적으로 나타내면 좋을듯
```
접두어 maybe - Optional maybeOrder
접두어 opt - Optional optOrder
```
하나 선택해서 적용해주시면 나머지도 통일하는걸로 할까요?

2018-08-31 19:40 UTC, opklnm102 commented on src/main/java/kr/co/mashup/mapc/service/BookingService.java
> +            log.info("asdkjhasdj");
디버깅시 사용했던 log들은 삭제하면 좋을듯해요

2018-08-31 19:40 UTC, opklnm102 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://key-rds.cy2pmafzldzf.ap-northeast-2.rds.amazonaws.com/SeoulAppContest?useUnicode=true&charaterEncoding=utf-8&useSSL=false
그만 바꿔주세요...

2018-08-31 20:51 UTC, KiWooyoung commented on src/main/java/kr/co/mashup/mapc/dto/BookingDto.java
> +            log.info(this.toString());
인정..

2018-08-31 20:52 UTC, KiWooyoung commented on src/main/java/kr/co/mashup/mapc/service/BookingService.java
> +        Optional<Tourist> tourist = touristRepository.findByUuid(body.getUuid());
굿뜨

2018-08-31 20:54 UTC, KiWooyoung commented on src/main/java/kr/co/mashup/mapc/service/BookingService.java
> +        Optional<Tourist> tourist = touristRepository.findByUuid(body.getUuid());
maybe 가 좋을거 같아요 의미상?

2018-08-31 20:55 UTC, KiWooyoung commented on src/main/java/kr/co/mashup/mapc/service/BookingService.java
> +            log.info("asdkjhasdj");
삭제 인정

2018-08-31 20:57 UTC, KiWooyoung commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://key-rds.cy2pmafzldzf.ap-northeast-2.rds.amazonaws.com/SeoulAppContest?useUnicode=true&charaterEncoding=utf-8&useSSL=false
똬르르

2018-09-12 17:24 UTC, opklnm102 commented
이건 conflict가 많기도 하고 수정이 생기지도 않아서 여기서 close하고 수정 후 수동으로 머지해둘께요

2018-09-12 17:24 UTC, closed without merging